version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: pub-cache
    restart: on-failure
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./dbdata:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend

  cache-init:
    image: redis/redis-stack:latest
    container_name: pub-cache-init
    volumes:
      - ./dbdata:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    command: sh -c 'chmod +x /data/load-redis.sh && /data/load-redis.sh cache'
    networks:
      - frontend
      - backend
    depends_on:
      cache:
        condition: service_started

  poll-api:
    image: poll-api:0.1
    container_name: poll-api-1
    restart: always
    ports:
      - '1080:1080'
    depends_on:
      cache-init:
        condition: service_completed_successfully
    environment:
      - PUBAPI_CACHE_URL=cache:6379
    networks:
      - frontend
      - backend

  vote-api:
    image: vote-api:0.1
    container_name: vote-api-1
    restart: always
    ports:
      - '2080:2080'
    depends_on:
      cache-init:
        condition: service_completed_successfully
    environment:
      - RLAPI_CACHE_URL=cache:6379
      - RLAPI_PUB_API_URL=http://poll-api:1080 
    networks:
      - frontend
      - backend

  voter-api:
    image: voter-api:0.1
    container_name: voter-api-1
    restart: always
    ports:
      - '3080:3080'
    depends_on:
      cache-init:
        condition: service_completed_successfully
    environment:
      - RLAPI_CACHE_URL=cache:6379
      - RLAPI_PUB_API_URL=http://poll-api:1080 
    networks:
      - frontend
      - backend


networks:
  frontend:
    internal: false
  backend:
    internal: true