version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: pub-cache
    restart: on-failure
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./dbdata:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend

  cache-init:
    image: redis/redis-stack:latest
    container_name: pub-cache-init
    volumes:
      - ./dbdata:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    command: sh -c 'chmod +x /data/load-redis.sh && /data/load-redis.sh cache'
    networks:
      - frontend
      - backend

networks:
  frontend:
    internal: false
  backend:
    internal: true